-- MySQL Script generated by MySQL Workbench
-- Thu Jul 14 15:01:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `cve_cat` INT NOT NULL AUTO_INCREMENT,
  `nom_cat` ENUM("Adulto", "Infantil") NOT NULL,
  PRIMARY KEY (`cve_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA_PRENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA_PRENDA` (
  `cve_pcat` INT NOT NULL AUTO_INCREMENT,
  `prenda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cve_pcat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GENERO` (
  `cve_gen` INT NOT NULL AUTO_INCREMENT,
  `genero` ENUM("Masculino", "Femenino") NOT NULL,
  PRIMARY KEY (`cve_gen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IMAGENES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IMAGENES` (
  `cve_img` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(250) NOT NULL,
  `nom` VARCHAR(50) NULL,
  PRIMARY KEY (`cve_img`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTOS` (
  `cve_prod` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `exitencia` NVARCHAR(10) NULL,
  `talla` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `categoria` INT NOT NULL,
  `categoria_prenda` INT NULL,
  `genero` INT NULL,
  `imagen` INT NULL,
  PRIMARY KEY (`cve_prod`),
  CONSTRAINT `cat_fk_prod`
    FOREIGN KEY (`categoria`)
    REFERENCES `mydb`.`CATEGORIA` (`cve_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `catp_fk_prod`
    FOREIGN KEY (`categoria_prenda`)
    REFERENCES `mydb`.`CATEGORIA_PRENDA` (`cve_pcat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gen_fk_prod`
    FOREIGN KEY (`genero`)
    REFERENCES `mydb`.`GENERO` (`cve_gen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `img_fk_prod`
    FOREIGN KEY (`imagen`)
    REFERENCES `mydb`.`IMAGENES` (`cve_img`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `tel_celular` VARCHAR(10) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usr` INT NOT NULL AUTO_INCREMENT,
  `correo` NVARCHAR(50) NOT NULL,
  `contraseña` NVARCHAR(45) NOT NULL,
  `persona` INT NULL,
  PRIMARY KEY (`id_usr`),
  CONSTRAINT `persona_usr_FK`
    FOREIGN KEY (`persona`)
    REFERENCES `mydb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORDEN` (
  `reg` INT NOT NULL AUTO_INCREMENT,
  `fecha_orden` DATE NULL,
  `usr` INT NULL,
  PRIMARY KEY (`reg`),
  CONSTRAINT `usr_ord_FK`
    FOREIGN KEY (`usr`)
    REFERENCES `mydb`.`USUARIO` (`id_usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_ORDEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_ORDEN` (
  `reg_det` INT NOT NULL AUTO_INCREMENT,
  `orden` INT NOT NULL,
  `fecha_detalle` DATE NOT NULL,
  `producto` INT NOT NULL,
  `unidades` INT NOT NULL,
  PRIMARY KEY (`reg_det`),
  CONSTRAINT `orden_fk_detalle`
    FOREIGN KEY (`orden`)
    REFERENCES `mydb`.`ORDEN` (`reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prod_fk_detalle`
    FOREIGN KEY (`producto`)
    REFERENCES `mydb`.`PRODUCTOS` (`cve_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;